---
mariadb_repo_setup_checksum: >-
  sha256:73f4ab14ccc3ceb8c03bb283dd131a3235cfc28086475f43e9291d2060d48c97
mariadb_version: 'mariadb-12.1'

mariadb_certs:
  ca_path: /etc/mysql/mariadb_ca.crt
  cert_path: /etc/mysql/mariadb.crt
  key_path: /etc/mysql/mariadb.key
  ca_content: '{{ lookup("ansible.builtin.file",
    "secrets/certs/ca.crt") }}'
  cert_content: '{{ lookup("ansible.builtin.file",
    "secrets/{{ inventory_hostname }}.crt") }}'
  key_content: '{{ lookup("ansible.builtin.file",
    "secrets/{{ inventory_hostname }}.key") }}'

mariadb_config: |
  [client-server]
  socket = "/run/mysqld/mysqld.sock"

  [mariadbd]
  pid_file = "/run/mysqld/mysqld.pid"
  basedir = "/usr"
  {%
    set config = mariadb_config_default |
      ansible.builtin.combine(mariadb_config_override)
  %}
  {% for key, value in config.items() %}
  {% if value is boolean %}
  {{- key }} = {{ '1' if value else '0' }}
  {% elif value is number %}
  {{- key }} = {{ value }}
  {% else %}
  {{- key }} = "{{ value }}"
  {% endif %}
  {% endfor %}

mariadb_config_default:
  bind_address: '127.0.0.1'
  expire_logs_days: 10
  server_id: 0
  gtid_domain_id: 0
  gtid_strict_mode: true
  skip_name_resolve: true
  wait_timeout: 60
  log_bin: true
  log_basename: mariadb
  binlog_format: ROW
  binlog_expire_logs_seconds: 604800
  max_binlog_size: 16M
mariadb_config_override: {}

mariadb_confd_files: {}
...
