---
- name: Restart consul service
  ansible.builtin.systemd_service:
    name: consul.service
    state: restarted
  ignore_errors: '{{ ansible_check_mode }}'

- name: Reload consul service
  ansible.builtin.systemd_service:
    name: consul.service
    state: reloaded
  ignore_errors: '{{ ansible_check_mode }}'
...
